### Question1

In [4]:
# Yes, there is a difference in the data types of the variables list_ and array_list. list_ is a Python list containing strings, while 
# array_list is a NumPy array. The elements in list_ are of type str, whereas the elements in array_list will be of type numpy.str_ or 
# numpy.object_.

# To print the data types of both variables, you can use the type() function. Here's the code:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", type(array_list[0]))

# The above code will output the data types of the first element of list_ and array_list. Since all elements in list_ have the same data
# type, printing the data type of the first element is sufficient.

Data type of list_: <class 'str'>
Data type of array_list: <class 'numpy.str_'>


### Question2

In [1]:
# To print the data type of each element in both list_ and array_list, you can iterate over the elements and use the type() function to
# determine the data type. Here's the code:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

# The above code will iterate over each element in list_ and array_list respectively and print the data type of each element. It will
# output the data types of elements in list_ first, followed by the data types of elements in array_list.

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Question3

In [2]:
# Yes, there will be a difference in the data types of the elements present in list_ and array_list when the dtype parameter is set to int
# during the creation of array_list. The elements in list_ are originally strings, while array_list will be explicitly converted to 
# integers.

# To print the data types of each element in both list_ and array_list after the changes, you can iterate over the elements and use the
# type() function. Here's the updated code:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

# The above code will iterate over each element in list_ and array_list, respectively, and print the data type of each element. It will 
# output the data types of elements in list_ first, followed by the data types of elements in the converted array_list, which will be of 
# type int.

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Question4

In [3]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Size
size = num_array.size
print("Size of num_array:", size)

# In the code above, we first import the NumPy library as np. Then, we create the num_list variable as a nested list. Next, we convert
# num_list into a NumPy array called num_array.

# To find the shape, we use the shape attribute of num_array and store it in the shape variable. The shape attribute returns a tuple 
# representing the dimensions of the array.

# To find the size, we use the size attribute of num_array and store it in the size variable. The size attribute returns the total number
# of elements in the array.

Shape of num_array: (2, 3)
Size of num_array: 6


### Question5

In [4]:
# To create a NumPy array of a 3x3 matrix containing only zeros, you can use the np.zeros() function. Here's the code:

import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)

# In the code above, we import the NumPy library as np. We then use the np.zeros() function to create an array of zeros. The function takes
# the desired shape of the array as a tuple (3, 3).

# The resulting zeros_array will be a 3x3 NumPy array filled with zeros. When we print zeros_array, it will output: 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Question6

In [5]:
# To create an identity matrix of shape (5,5) using NumPy functions, you can use the np.eye() function. Here's the code:

import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)

# In the code above, we import the NumPy library as np. We then use the np.eye() function to create an identity matrix. The function takes 
# the desired size of the matrix as an argument, in this case, 5.

# The resulting identity_matrix will be a 5x5 NumPy array representing the identity matrix.


# The identity matrix is a square matrix where all the diagonal elements are 1 and all other elements are 0.


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
